{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "07a5392c-1459-427d-b930-889b887a7c2a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['CUDA_VISIBLE_DEVICES']='4'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1716e38c-d330-4e67-b89c-be073b2b79ff",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: PyDrive in ./.local/lib/python3.10/site-packages (1.3.1)\n",
      "Requirement already satisfied: google-api-python-client>=1.2 in ./.local/lib/python3.10/site-packages (from PyDrive) (2.79.0)\n",
      "Requirement already satisfied: oauth2client>=4.0.0 in ./.local/lib/python3.10/site-packages (from PyDrive) (4.1.3)\n",
      "Requirement already satisfied: PyYAML>=3.0 in ./.conda/envs/urecar/lib/python3.10/site-packages (from PyDrive) (6.0.2)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (0.22.0)\n",
      "Requirement already satisfied: google-auth<3.0.0dev,>=1.19.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (2.16.1)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.1.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (0.1.0)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (2.11.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in ./.local/lib/python3.10/site-packages (from google-api-python-client>=1.2->PyDrive) (4.1.1)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in ./.local/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (0.6.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in ./.local/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (0.4.1)\n",
      "Requirement already satisfied: rsa>=3.1.4 in ./.local/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (4.9)\n",
      "Requirement already satisfied: six>=1.6.1 in ./.conda/envs/urecar/lib/python3.10/site-packages (from oauth2client>=4.0.0->PyDrive) (1.16.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in ./.local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (1.58.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in ./.local/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (4.25.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in ./.conda/envs/urecar/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (2.32.3)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=1.2->PyDrive) (5.5.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.local/lib/python3.10/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client>=1.2->PyDrive) (3.1.4)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (3.8)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.2->PyDrive) (2024.8.30)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install PyDrive"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f21d47bf-e526-4e43-bbd7-dfe9dab5df2d",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://download.pytorch.org/whl/cu118\n",
      "Collecting torch\n",
      "  Using cached https://download.pytorch.org/whl/cu118/torch-2.4.1%2Bcu118-cp310-cp310-linux_x86_64.whl (857.6 MB)\n",
      "Collecting torchvision\n",
      "  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.19.1%2Bcu118-cp310-cp310-linux_x86_64.whl (6.3 MB)\n",
      "Collecting filelock (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)\n",
      "Collecting typing-extensions>=4.8.0 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/typing_extensions-4.9.0-py3-none-any.whl (32 kB)\n",
      "Collecting sympy (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)\n",
      "Collecting networkx (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)\n",
      "Collecting jinja2 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/Jinja2-3.1.3-py3-none-any.whl (133 kB)\n",
      "Collecting fsspec (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/fsspec-2024.2.0-py3-none-any.whl (170 kB)\n",
      "Collecting nvidia-cuda-nvrtc-cu11==11.8.89 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cuda_nvrtc_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (23.2 MB)\n",
      "Collecting nvidia-cuda-runtime-cu11==11.8.89 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)\n",
      "Collecting nvidia-cuda-cupti-cu11==11.8.87 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)\n",
      "Collecting nvidia-cudnn-cu11==9.1.0.70 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cudnn_cu11-9.1.0.70-py3-none-manylinux2014_x86_64.whl (663.9 MB)\n",
      "Collecting nvidia-cublas-cu11==11.11.3.6 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)\n",
      "Collecting nvidia-cufft-cu11==10.9.0.58 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)\n",
      "Collecting nvidia-curand-cu11==10.3.0.86 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_curand_cu11-10.3.0.86-py3-none-manylinux1_x86_64.whl (58.1 MB)\n",
      "Collecting nvidia-cusolver-cu11==11.4.1.48 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cusolver_cu11-11.4.1.48-py3-none-manylinux1_x86_64.whl (128.2 MB)\n",
      "Collecting nvidia-cusparse-cu11==11.7.5.86 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)\n",
      "Collecting nvidia-nccl-cu11==2.20.5 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_nccl_cu11-2.20.5-py3-none-manylinux2014_x86_64.whl (142.9 MB)\n",
      "Collecting nvidia-nvtx-cu11==11.8.86 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/cu118/nvidia_nvtx_cu11-11.8.86-py3-none-manylinux1_x86_64.whl (99 kB)\n",
      "Collecting triton==3.0.0 (from torch)\n",
      "  Using cached https://download.pytorch.org/whl/triton-3.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (209.4 MB)\n",
      "Collecting numpy (from torchvision)\n",
      "  Using cached https://download.pytorch.org/whl/numpy-1.26.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)\n",
      "Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)\n",
      "  Using cached https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)\n",
      "Collecting MarkupSafe>=2.0 (from jinja2->torch)\n",
      "  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)\n",
      "Collecting mpmath>=0.19 (from sympy->torch)\n",
      "  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: mpmath, typing-extensions, sympy, pillow, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, numpy, networkx, MarkupSafe, fsspec, filelock, triton, nvidia-cusolver-cu11, nvidia-cudnn-cu11, jinja2, torch, torchvision\n",
      "  Attempting uninstall: mpmath\n",
      "    Found existing installation: mpmath 1.3.0\n",
      "    Uninstalling mpmath-1.3.0:\n",
      "      Successfully uninstalled mpmath-1.3.0\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing_extensions 4.9.0\n",
      "    Uninstalling typing_extensions-4.9.0:\n",
      "      Successfully uninstalled typing_extensions-4.9.0\n",
      "  Attempting uninstall: sympy\n",
      "    Found existing installation: sympy 1.12\n",
      "    Uninstalling sympy-1.12:\n",
      "      Successfully uninstalled sympy-1.12\n",
      "\u001b[33m  WARNING: The script isympy is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: pillow\n",
      "    Found existing installation: pillow 10.2.0\n",
      "    Uninstalling pillow-10.2.0:\n",
      "      Successfully uninstalled pillow-10.2.0\n",
      "  Attempting uninstall: nvidia-nvtx-cu11\n",
      "    Found existing installation: nvidia-nvtx-cu11 11.8.86\n",
      "    Uninstalling nvidia-nvtx-cu11-11.8.86:\n",
      "      Successfully uninstalled nvidia-nvtx-cu11-11.8.86\n",
      "  Attempting uninstall: nvidia-nccl-cu11\n",
      "    Found existing installation: nvidia-nccl-cu11 2.20.5\n",
      "    Uninstalling nvidia-nccl-cu11-2.20.5:\n",
      "      Successfully uninstalled nvidia-nccl-cu11-2.20.5\n",
      "  Attempting uninstall: nvidia-cusparse-cu11\n",
      "    Found existing installation: nvidia-cusparse-cu11 11.7.5.86\n",
      "    Uninstalling nvidia-cusparse-cu11-11.7.5.86:\n",
      "      Successfully uninstalled nvidia-cusparse-cu11-11.7.5.86\n",
      "  Attempting uninstall: nvidia-curand-cu11\n",
      "    Found existing installation: nvidia-curand-cu11 10.3.0.86\n",
      "    Uninstalling nvidia-curand-cu11-10.3.0.86:\n",
      "      Successfully uninstalled nvidia-curand-cu11-10.3.0.86\n",
      "  Attempting uninstall: nvidia-cufft-cu11\n",
      "    Found existing installation: nvidia-cufft-cu11 10.9.0.58\n",
      "    Uninstalling nvidia-cufft-cu11-10.9.0.58:\n",
      "      Successfully uninstalled nvidia-cufft-cu11-10.9.0.58\n",
      "  Attempting uninstall: nvidia-cuda-runtime-cu11\n",
      "    Found existing installation: nvidia-cuda-runtime-cu11 11.8.89\n",
      "    Uninstalling nvidia-cuda-runtime-cu11-11.8.89:\n",
      "      Successfully uninstalled nvidia-cuda-runtime-cu11-11.8.89\n",
      "  Attempting uninstall: nvidia-cuda-nvrtc-cu11\n",
      "    Found existing installation: nvidia-cuda-nvrtc-cu11 11.8.89\n",
      "    Uninstalling nvidia-cuda-nvrtc-cu11-11.8.89:\n",
      "      Successfully uninstalled nvidia-cuda-nvrtc-cu11-11.8.89\n",
      "  Attempting uninstall: nvidia-cuda-cupti-cu11\n",
      "    Found existing installation: nvidia-cuda-cupti-cu11 11.8.87\n",
      "    Uninstalling nvidia-cuda-cupti-cu11-11.8.87:\n",
      "      Successfully uninstalled nvidia-cuda-cupti-cu11-11.8.87\n",
      "  Attempting uninstall: nvidia-cublas-cu11\n",
      "    Found existing installation: nvidia-cublas-cu11 11.11.3.6\n",
      "    Uninstalling nvidia-cublas-cu11-11.11.3.6:\n",
      "      Successfully uninstalled nvidia-cublas-cu11-11.11.3.6\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.26.3\n",
      "    Uninstalling numpy-1.26.3:\n",
      "      Successfully uninstalled numpy-1.26.3\n",
      "\u001b[33m  WARNING: The script f2py is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: networkx\n",
      "    Found existing installation: networkx 3.2.1\n",
      "    Uninstalling networkx-3.2.1:\n",
      "      Successfully uninstalled networkx-3.2.1\n",
      "  Attempting uninstall: MarkupSafe\n",
      "    Found existing installation: MarkupSafe 2.1.5\n",
      "    Uninstalling MarkupSafe-2.1.5:\n",
      "      Successfully uninstalled MarkupSafe-2.1.5\n",
      "  Attempting uninstall: fsspec\n",
      "    Found existing installation: fsspec 2024.2.0\n",
      "    Uninstalling fsspec-2024.2.0:\n",
      "      Successfully uninstalled fsspec-2024.2.0\n",
      "  Attempting uninstall: filelock\n",
      "    Found existing installation: filelock 3.13.1\n",
      "    Uninstalling filelock-3.13.1:\n",
      "      Successfully uninstalled filelock-3.13.1\n",
      "  Attempting uninstall: triton\n",
      "    Found existing installation: triton 3.0.0\n",
      "    Uninstalling triton-3.0.0:\n",
      "      Successfully uninstalled triton-3.0.0\n",
      "\u001b[33m  WARNING: The scripts proton and proton-viewer are installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: nvidia-cusolver-cu11\n",
      "    Found existing installation: nvidia-cusolver-cu11 11.4.1.48\n",
      "    Uninstalling nvidia-cusolver-cu11-11.4.1.48:\n",
      "      Successfully uninstalled nvidia-cusolver-cu11-11.4.1.48\n",
      "  Attempting uninstall: nvidia-cudnn-cu11\n",
      "    Found existing installation: nvidia-cudnn-cu11 9.1.0.70\n",
      "    Uninstalling nvidia-cudnn-cu11-9.1.0.70:\n",
      "      Successfully uninstalled nvidia-cudnn-cu11-9.1.0.70\n",
      "  Attempting uninstall: jinja2\n",
      "    Found existing installation: Jinja2 3.1.3\n",
      "    Uninstalling Jinja2-3.1.3:\n",
      "      Successfully uninstalled Jinja2-3.1.3\n",
      "  Attempting uninstall: torch\n",
      "    Found existing installation: torch 2.4.1+cu118\n",
      "    Uninstalling torch-2.4.1+cu118:\n",
      "      Successfully uninstalled torch-2.4.1+cu118\n",
      "\u001b[33m  WARNING: The scripts convert-caffe2-to-onnx, convert-onnx-to-caffe2 and torchrun are installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m  Attempting uninstall: torchvision\n",
      "    Found existing installation: torchvision 0.19.1+cu118\n",
      "    Uninstalling torchvision-0.19.1+cu118:\n",
      "      Successfully uninstalled torchvision-0.19.1+cu118\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.2.0 jinja2-3.1.3 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.3 nvidia-cublas-cu11-11.11.3.6 nvidia-cuda-cupti-cu11-11.8.87 nvidia-cuda-nvrtc-cu11-11.8.89 nvidia-cuda-runtime-cu11-11.8.89 nvidia-cudnn-cu11-9.1.0.70 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.3.0.86 nvidia-cusolver-cu11-11.4.1.48 nvidia-cusparse-cu11-11.7.5.86 nvidia-nccl-cu11-2.20.5 nvidia-nvtx-cu11-11.8.86 pillow-10.2.0 sympy-1.12 torch-2.4.1+cu118 torchvision-0.19.1+cu118 triton-3.0.0 typing-extensions-4.9.0\n"
     ]
    }
   ],
   "source": [
    "# pip install torch torchvision torchaudio\n",
    "# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118\n",
    "# !pip install torchvision --upgrade --index-url https://download.pytorch.org/whl/cu118\n",
    "# !pip install --upgrade torchvision --index-url https://download.pytorch.org/whl/cu118\n",
    "!pip install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu118"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5095d88f-82bc-4dc6-9413-a43ca1c1a7f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting opencv-python\n",
      "  Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\n",
      "Requirement already satisfied: numpy>=1.21.2 in ./.local/lib/python3.10/site-packages (from opencv-python) (1.26.3)\n",
      "Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.5 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.5/62.5 MB\u001b[0m \u001b[31m60.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: opencv-python\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed opencv-python-4.10.0.84\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting opencv-python-headless\n",
      "  Downloading opencv_python_headless-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\n",
      "Requirement already satisfied: numpy>=1.21.2 in ./.local/lib/python3.10/site-packages (from opencv-python-headless) (1.26.3)\n",
      "Downloading opencv_python_headless-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.9 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m49.9/49.9 MB\u001b[0m \u001b[31m44.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: opencv-python-headless\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed opencv-python-headless-4.10.0.84\n"
     ]
    }
   ],
   "source": [
    "!pip install opencv-python\n",
    "!pip install opencv-python-headless"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "7c4d7728-27f4-4f60-a784-b917b345cfa1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: torchvision in ./.local/lib/python3.10/site-packages (0.19.1+cu118)\n",
      "Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from torchvision) (1.26.3)\n",
      "Requirement already satisfied: torch==2.4.1 in ./.local/lib/python3.10/site-packages (from torchvision) (2.4.1+cu118)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./.local/lib/python3.10/site-packages (from torchvision) (10.2.0)\n",
      "Requirement already satisfied: filelock in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (4.9.0)\n",
      "Requirement already satisfied: sympy in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (1.12)\n",
      "Requirement already satisfied: networkx in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.1.3)\n",
      "Requirement already satisfied: fsspec in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (2024.2.0)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.89)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.89)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.87)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (9.1.0.70)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.11.3.6)\n",
      "Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (10.9.0.58)\n",
      "Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (10.3.0.86)\n",
      "Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.4.1.48)\n",
      "Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.7.5.86)\n",
      "Requirement already satisfied: nvidia-nccl-cu11==2.20.5 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (2.20.5)\n",
      "Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (11.8.86)\n",
      "Requirement already satisfied: triton==3.0.0 in ./.local/lib/python3.10/site-packages (from torch==2.4.1->torchvision) (3.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.10/site-packages (from jinja2->torch==2.4.1->torchvision) (2.1.5)\n",
      "Requirement already satisfied: mpmath>=0.19 in ./.local/lib/python3.10/site-packages (from sympy->torch==2.4.1->torchvision) (1.3.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install torchvision"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "fa159485-5636-4044-8427-f1b3d4222764",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-api-core==2.11.0 in ./.local/lib/python3.10/site-packages (2.11.0)\n",
      "Requirement already satisfied: google-api-python-client==2.79.0 in ./.local/lib/python3.10/site-packages (2.79.0)\n",
      "Requirement already satisfied: google-auth==2.16.1 in ./.local/lib/python3.10/site-packages (2.16.1)\n",
      "Requirement already satisfied: google-auth-httplib2==0.1.0 in ./.local/lib/python3.10/site-packages (0.1.0)\n",
      "Collecting google-auth-oauthlib==0.4.1\n",
      "  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: googleapis-common-protos==1.58.0 in ./.local/lib/python3.10/site-packages (1.58.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in ./.local/lib/python3.10/site-packages (from google-api-core==2.11.0) (4.25.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-api-core==2.11.0) (2.32.3)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in ./.local/lib/python3.10/site-packages (from google-api-python-client==2.79.0) (0.22.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in ./.local/lib/python3.10/site-packages (from google-api-python-client==2.79.0) (4.1.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth==2.16.1) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.10/site-packages (from google-auth==2.16.1) (0.4.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-auth==2.16.1) (1.16.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./.local/lib/python3.10/site-packages (from google-auth==2.16.1) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib==0.4.1) (2.0.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.local/lib/python3.10/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client==2.79.0) (3.1.4)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth==2.16.1) (0.6.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.11.0) (2024.6.2)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.1) (3.2.2)\n",
      "Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: google-auth-oauthlib\n",
      "  Attempting uninstall: google-auth-oauthlib\n",
      "    Found existing installation: google-auth-oauthlib 1.2.1\n",
      "    Uninstalling google-auth-oauthlib-1.2.1:\n",
      "      Successfully uninstalled google-auth-oauthlib-1.2.1\n",
      "\u001b[33m  WARNING: The script google-oauthlib-tool is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed google-auth-oauthlib-0.4.1\n"
     ]
    }
   ],
   "source": [
    "!pip install google-api-core==2.11.0 google-api-python-client==2.79.0 google-auth==2.16.1 google-auth-httplib2==0.1.0 google-auth-oauthlib==0.4.1 googleapis-common-protos==1.58.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "d90370ba-e4b3-44d0-9c84-653f5ec14430",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-auth-oauthlib in ./.local/lib/python3.10/site-packages (0.4.1)\n",
      "Collecting google-auth-oauthlib\n",
      "  Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.16.1)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.0.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (0.4.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /opt/tljh/user/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (1.16.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (4.9)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\n",
      "Requirement already satisfied: requests>=2.0.0 in /opt/tljh/user/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.32.3)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-auth-oauthlib) (0.6.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2024.6.2)\n",
      "Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl (24 kB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: google-auth-oauthlib\n",
      "  Attempting uninstall: google-auth-oauthlib\n",
      "    Found existing installation: google-auth-oauthlib 0.4.1\n",
      "    Uninstalling google-auth-oauthlib-0.4.1:\n",
      "      Successfully uninstalled google-auth-oauthlib-0.4.1\n",
      "\u001b[33m  WARNING: The script google-oauthlib-tool is installed in '/home/j-j11a303/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed google-auth-oauthlib-1.2.1\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade google-auth-oauthlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "fb274325-d64c-4d53-9ce9-589f965716e3",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: requests in ./.conda/envs/urecar/lib/python3.10/site-packages (2.32.3)\n",
      "Requirement already satisfied: google-auth-oauthlib in ./.local/lib/python3.10/site-packages (1.2.1)\n",
      "Requirement already satisfied: google-auth-httplib2 in ./.local/lib/python3.10/site-packages (0.1.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests) (3.8)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests) (2024.8.30)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.16.1)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.10/site-packages (from google-auth-oauthlib) (2.0.0)\n",
      "Requirement already satisfied: httplib2>=0.15.0 in ./.local/lib/python3.10/site-packages (from google-auth-httplib2) (0.22.0)\n",
      "Requirement already satisfied: six in ./.conda/envs/urecar/lib/python3.10/site-packages (from google-auth-httplib2) (1.16.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (0.4.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./.local/lib/python3.10/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (4.9)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.local/lib/python3.10/site-packages (from httplib2>=0.15.0->google-auth-httplib2) (3.1.4)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in ./.conda/envs/urecar/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-auth-oauthlib) (0.6.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install requests google-auth-oauthlib google-auth-httplib2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "71050a0e-9c9f-4756-9733-90aee2f72995",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'nextPageToken': '~!!~AI9FV7RLC2PDURY3GIr9bX5yxf0KPER3ZcfXx5jIsRbkepGrXpxxtEF1SrP2zQaeiIM1B9Ajo0SP4JeIDB0Mrc3QAd1B-Z4fP7-KRq0tzVkDeQVXPZhmxEdcqSYkP_X-Y4sKNgNqIhKIAt76rfJyhdAmDik6joo2mSK4JjX-sLGgkPH49MzfznUdzRqa1KWV8NMHR5BITavPyxPzuv6kjfC8pWFV--wuYkgNVZ1Uvp7WMeeozRj29EBgBd4EKUSDSc4wr5WI4884eZkfnleCp0XeA6noJL-rtjlUMkGXLWp_NT13d0zO8yp1LEZQhAXh0tH7UknUyDjyitLHauXoEwT3IIlPHp-1PxYHPfRB3mLAX1H8rgJjO3Aqe6saXFQVx-6Z6emWhO_o6I4nDrWc08NszzmgLEFooHMR_EiB9nTRxPUbIS6JB8N78WaQ1cN2GkP_HwXm0OHVZINvLzqgcerChso0_K3zxhDobZCqXGGErzWsh2M18j8M7uZHVJ6D8--B-YsJmLBlNV7OOmWXGZBylxDD5JxG_4hrdR9qb6UZOUSxpAE9chI=', 'kind': 'drive#fileList', 'incompleteSearch': False, 'files': [{'kind': 'drive#file', 'mimeType': 'application/vnd.jgraph.mxfile', 'id': '19MhGtt2_sKhioPAx0tY6r1n3pS1alnYT', 'name': 'ssafy.drawio'}, {'kind': 'drive#file', 'mimeType': 'application/vnd.google-apps.presentation', 'id': '1pYgPLGPo1OOTeaswoVEKE4PPbNRtrwtxo0iCeObK_3U', 'name': '(특화)서울 3반'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1IW-a2ubcbPeT4V6wugkyOWhdRh-rphbO', 'name': '13서8264.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1HDM1Tpxedhxyb5_E1LdcUaJ1OibnoGyE', 'name': '13버4293.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1P7A1voL_i5dS545PRDvYEIvAxC_gJdB_', 'name': '07버8967.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1P92LQYx7zt8fATB9Uu26dzRqd7lZ_ycc', 'name': '07버7701.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1PC5NFvCf-k-L-8ySKIIZsi0YfMgY8N-8', 'name': '07버6233.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1PF7MUwEwB0Xx_Is53K-Ss-iOhJZwgcaI', 'name': '07버3981.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1PJQyOM-BG4M7-4s0VyNrBZFU7Ed40O8_', 'name': '07버1270.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1PM_f82B2vMI8aE1bTd6y-4Szb3aRV98J', 'name': '07버1064.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1PN8b2obI6z2bmSMKCc0gO1vuK4rO4Mvl', 'name': '07버0269.jpg'}, {'kind': 'drive#file', 'mimeType': 'image/jpeg', 'id': '1PQ4ax8mxybpHU-nsQr1sBdkP1cN6MO9S', 'name': '07무7733.jpg'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1foIJ3kuyu71y1BKPqFGng8sScpjCdP_4', 'name': '92라0979.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fHtCmv9PRULg-NmhyprvcXML1k55o-aK', 'name': '92도5577-60.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1frVzgoW8BT_28Py_iDSw6EwWHkAoxIo_', 'name': '92라0437.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gf72SG4QC2NGHQq_XLw0eBjAAbQPnAoI', 'name': '92마2666-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fMZAobELiOLcPKmoozRZed261tlPl38G', 'name': '92도5577-6.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gitDnZL7mw8LeQIPSVGCKBCBIBZ-AL4w', 'name': '92마2607.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fMk5Qnw1dc3j0bnXRE2sGC3S66ITxxlB', 'name': '92도5577-59.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gjAN5x-WV6kWDBJOPmL4I5nOqH61qyuV', 'name': '92마1007.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fNq2KpAp3yFAu8uXRMsdwIFHc3WCyyy8', 'name': '92도5577-58.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gjAz6TjtFsyhfqdCebJheN5wAplGzgmD', 'name': '92로9962.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fO45a-lT-mZzFtNQDcqg4K4ZlVy2qZVf', 'name': '92도5577-57.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1ft_17BpGL2WIUNl_oK3Z1kpuJjeRXoNO', 'name': '92라0437-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1golCL-m5KPY3ZKewy2mSr0ievz2Jcuvn', 'name': '92로8124.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fOMu5A3YbrSNnJRgTY_abqAwYQGw5mYZ', 'name': '92도5577-56.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fu7ZLXQ_SD8Ks73xxXTxuyXGk30I-jPl', 'name': '92도8015.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gq-s4PAgl7FpiObWKuJhIXUmDq5VRcjc', 'name': '92로8103.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fuBMg9_usECRbeZcTBo9SZM9YCfV8O2j', 'name': '92도5577.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fSFrDfoUyEI_NerWcO_V9q-CQOcnaObp', 'name': '92도5577-55.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1grzFKjC1YojIiYb2ROi1Zq97t4z1ZJzK', 'name': '92로8103-3.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fuHKfbxLOdoUB_jYt4TWNdTQHKTFIY67', 'name': '92도5577-9.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fU7vKLX2y51IefbCeG039dwKqtmSJ0uR', 'name': '92도5577-54.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gsnLaDfMaKPnQiTD305DNG2Zjr8V5QPQ', 'name': '92로8103-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g-9axybswaGg37j3pK9lRimWx2sKXj6B', 'name': '92도5577-8.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fWAWHGY-xhkELwbXkoGhtyeyABR4-uo5', 'name': '92도5577-53.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gtGByq9ltwnO7jq4EdYaXIHV2qnlSgoM', 'name': '92로6757.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g1_ij7QqfdZnXaP1MudueZcB_AZiKm_P', 'name': '92도5577-7.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fWrFvXLkDTs98JwkO53SGPn5wRenWIT_', 'name': '92도5577-52.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gtTzP0XMTpaQhhOxiaDSRc1FtNDHINAg', 'name': '92로6739.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g1kQYlDw8wegtpSpHbLVw4A0qRxQaX0v', 'name': '92도5577-67.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fd-CD1IaaanlTyPZYf2Y2uu3mVl2zOV1', 'name': '92도5577-51.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g45MVml49iZM2V55A9CgZNmF4sDI2zf2', 'name': '92도5577-66.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gu26Zgm1kPh-seEgzxY_ij7mby6yWT1z', 'name': '92로6739-9.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fdVDFGFzS8S7RJHAzEUW1-v6nd45aXPc', 'name': '92도5577-50.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g6zPFLAPHjRo5TfeEMouira2BcSBOiY9', 'name': '92도5577-65.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1ffgTHmjK4wUuldFwyVjCylOujrjeO3ZK', 'name': '92도5577-5.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g8WQY6W4lAiUgZeLxBXB-NLv-E4pAya_', 'name': '92도5577-64.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1guG8baK1bY44Nk6wQAMXMtLJ8Ddsmaja', 'name': '92로6739-8.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gzSYw-wUUQqo8UsFxJGcDQJcLTjD4sVU', 'name': '92로6739-7.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1g9u1Om83kFPbniovL7vl7ejjkdJgOxwA', 'name': '92도5577-63.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fgZF5_KUe7zbBLqb4IK_YTLA1nMdZItW', 'name': '92도5577-49.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1h-61MtdYF5JHF2ei-6LK0qdG0Qd84I0u', 'name': '92로6739-6.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gE3b8jRP46sjiTH4hRg9xJX6oXi1E_U_', 'name': '92도5577-62.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1fi0VrlHT3MBM9jV2TEVc1QrMUbTZPLcS', 'name': '92도5577-48.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1h18Nu5BX0IX7jJnsZHYv1gJUvIopTYID', 'name': '92로6739-5.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1gFLhO7Oty_35E8ZBg4PWFImZ3pWKOTLm', 'name': '92도5577-61.json'}, {'kind': 'drive#file', 'mimeType': 'application/vnd.google-apps.folder', 'id': '1jYZlhZJW94-34-DKpALvsauuoKL4s_Yh', 'name': '[원천]자동차번호판OCR데이터'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1_pFI0Y5k1tWPUX4vRBjUsfJdaOCk79CO', 'name': '69서2723.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1_urDt72Yp9bAqKN31z-rEY8YH_R2OgYN', 'name': '69서2501.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1_x8xen49Y72Sy0PFeE71cx-o9Um_4N8x', 'name': '69서2200.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1_ys_DsNtI0Bgemx7zvtm6o__qpRPU6_f', 'name': '69서2200-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1cmoFLWHrwt9ayKfRe0OGHyPjcdEDr_Me', 'name': '69소2411-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1a-wHI1LAvSvht-2DAUA7Dj2JYnEN9aoD', 'name': '69서1658.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1cwiTA6RzA6-64i58iZ6q8NNy-3Jx1i3F', 'name': '69소2370.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1Q-TahyBDxzGWDdl1Tl03IY0JlbUS2Je9', 'name': '69두9103-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1b5-qfwe-KWh3frgi2peY5_7KA6No3YFg', 'name': '69서6114.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QOueZ27zw-f1kqHhiqrjdgsohn5Rx-EU', 'name': '69두0882.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1Zml43n63NCo5y2z9sM9ej66og45vgUda', 'name': '69보6181.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1b8TVh-u6rcdUL6W7HR8P6UwkYoR3bg2d', 'name': '69소2370-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QPRpaKoqyfkDK2YPPiUyRwRplF97IWoK', 'name': '69두0231.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1Y48vk1GcXiafo82pZvgbrHgZPYVbMFAm', 'name': '69버7628.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1bFyper7f0pznFkXk4ZNAYy4BFNy4bGo0', 'name': '69소2310.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QR13Llmk2z_ZlSVFekXzK9D8MSE0ZA8l', 'name': '69도9629.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1bG_50_YveWnTEDGEc-ZK0bFZgsmOSeF-', 'name': '69소2303.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1Y5qdgmzJQfbFcmoNplG_SgZp0X1NV_um', 'name': '69버7551.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1bU2BEftac2_NU-OW_5xFfLwRXwyAoAgu', 'name': '69소2297.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1YNAK8paABi_UQkllWRDC7TgkjE3TQ8xT', 'name': '69버7287.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QRRIOoEKmn9QE9PqZ9hTx9oj08jorav4', 'name': '69도9629-3.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1bUeiZRBYuOdsYsatJ9TdQSJbV8JHhgm6', 'name': '69소2295.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1YOLRJADZsUIP5DZAtNdIsetyiGbeBXEe', 'name': '69버7237.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QT4hiv4BJtgOaJgrouTG6H8zeVouCQLB', 'name': '69도9519.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1VuS-ZyI2nkdwMmL6RIsDsB-8cDB1l-Do', 'name': '69머8397-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1bahGXCyqdvbk1LW5luFaHG4JuzohGvA3', 'name': '69소2274.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1YUnQRB5OuCm4SyCWhcWulvQg8StZS0aa', 'name': '69버7145.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1V9dwpRSEkBtIm5nd4e-K7AixBPE4WGSv', 'name': '69마4698-3.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QaISgQw0UmRuPfmn0umE9_xSzm7zecL1', 'name': '69도9519-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1VvBI9zrougLtCEOxROJcWvfZT_FeVPeO', 'name': '69머7156.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1VCl-knqPPq_98gfpYZQ6oFfAqDDQ-iGA', 'name': '69마4698-2.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1Vz3Ado87RM_2EMFaSwFolsU7VJgNwHkQ', 'name': '69머5728.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1VEh4an6oXiwElNg2Yn7SIrJ3kH3lvt6Y', 'name': '69마3969.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1W0WSE0cwNhI1dRqlma1F2dkbmE19_n_G', 'name': '69머5221.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1VF1KVhBkZuZIot91OtZaOxZg2BD306Tf', 'name': '69마3729.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1SWdWonkG8X2Ccqf3fnnizRmhIMNfbFAU', 'name': '69러3466.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1OpSFy5S4kOE92IaaxbZNtFdGm8bbZtTl', 'name': '69더3313.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1YYoohjFvPJ4cjNAHT3bV_zCgAWgBCPPL', 'name': '69버6902.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1QaZJbAw4D5l7nECoqdeNRd7LTI1o6Got', 'name': '69도9380.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1bauekM_xnLhiFuBuouX4Klnezqp5wT6o', 'name': '69소2270.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1VJ4elZATLlnfHLgXaAl0416laP5-1cik', 'name': '69마3334.json'}, {'kind': 'drive#file', 'mimeType': 'application/json', 'id': '1W1SHRMX10H2HErNh59OAs3QY-uNKjZm_', 'name': '69머5219.json'}]}\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "from google.oauth2.credentials import Credentials\n",
    "from google_auth_oauthlib.flow import InstalledAppFlow\n",
    "from google.auth.transport.requests import Request\n",
    "import os\n",
    "\n",
    "# OAuth 2.0 클라이언트 ID를 사용하여 인증\n",
    "SCOPES = ['https://www.googleapis.com/auth/drive.readonly']\n",
    "\n",
    "# OAuth 2.0 인증 설정\n",
    "def authenticate():\n",
    "    creds = None\n",
    "    if os.path.exists('token.json'):\n",
    "        creds = Credentials.from_authorized_user_file('token.json', SCOPES)\n",
    "    if not creds or not creds.valid:\n",
    "        if creds and creds.expired and creds.refresh_token:\n",
    "            creds.refresh(Request())\n",
    "        else:\n",
    "            # flow = InstalledAppFlow.from_client_secrets_file(\n",
    "            #     'client_secrets.json', SCOPES)\n",
    "            # creds = flow.run_local_server(port=0)\n",
    "            auth_url, _ = flow.authorization_url(prompt='consent')\n",
    "            print(f'Please go to this URL: {auth_url}')\n",
    "\n",
    "            # 사용자가 브라우저에서 인증 후, 제공된 코드를 콘솔에 입력하도록 설정\n",
    "            code = input('Enter the authorization code: ')\n",
    "            creds = flow.fetch_token(code=code)\n",
    "        with open('token.json', 'w') as token:\n",
    "            token.write(creds.to_json())\n",
    "    return creds\n",
    "\n",
    "# Google Drive API 호출\n",
    "def list_files(creds):\n",
    "    url = 'https://www.googleapis.com/drive/v3/files'\n",
    "    headers = {'Authorization': f'Bearer {creds.token}'}\n",
    "    response = requests.get(url, headers=headers)\n",
    "    return response.json()\n",
    "\n",
    "creds = authenticate()\n",
    "files = list_files(creds)\n",
    "print(files)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7557f53b-4959-4251-b1e3-42f369314e13",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Go to the following link in your browser:\n",
      "\n",
      "    https://accounts.google.com/o/oauth2/auth?client_id=20853731651-6grrfq6n7htqhferl1ah8imldetrgg53.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code\n",
      "\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter verification code:  4/1AQlEd8yXnePXLqVPmZGQU6SWfpPZdHNMOJAtcRn8dbtkQOTL8ahbHjOQhpw\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Authentication successful.\n"
     ]
    }
   ],
   "source": [
    "from pydrive.auth import GoogleAuth\n",
    "from pydrive.drive import GoogleDrive\n",
    "import os\n",
    "# Google OAuth 인증 절차\n",
    "gauth = GoogleAuth()\n",
    "gauth.CommandLineAuth()  # 이 과정을 통해 브라우저가 열리고, Google 계정 인증이 이루어짐\n",
    "\n",
    "# gauth.SaveCredentialsFile(\"credentials.json\")\n",
    "drive = GoogleDrive(gauth)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "5256d809-5c84-4a30-ba91-6e47e218d992",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading [25627]A_BLUE from 1gJlW3MUBThDyO-_iIpS4BMZ25q-TA-yz\n",
      "Downloading [25625]A_BLUE from 1gSBfmYeeniUCI2n8x19Al_wLLa0zyh4A\n",
      "Downloading [25624]A_BLUE from 1fisR3NTOTPEVTNu1c4g5Mddi3bDybdKj\n",
      "Downloading [25623]A_BLUE from 1fzcsGagM_UhD2562HlfbwqhH6gKBzXWn\n",
      "Downloading [25621]A_BLUE from 1g8JGp0skZFureyeNbxyvINXSkcuaiug1\n",
      "Downloading [25619]A_BLUE from 1f_QoBQ5gQU0dlZjhGO2HJQQ9EAYtV4gs\n",
      "Downloading [25618]A_BLUE from 1fdglPKW3ib7obSCIICFFTQjUYw5Z9eZd\n",
      "Downloading [25617]A_BLUE from 1fhOHHVhT7Yrkn0S2HJFulKt1dgFm3dBU\n",
      "Downloading [25593]A_BLUE from 1f90W58tinUSahUTum3mZQZn4jwimVwRz\n",
      "Downloading [25591]A_BLUE from 1fTB9D2bXNgL1LL3HyR0927TnWae4Edp7\n"
     ]
    }
   ],
   "source": [
    "# import os\n",
    "# folder_id = '1Nby_3Fg7NZ-CpLDjimVm9cC3n3imW4Sd'\n",
    "# file_list = drive.ListFile({'q': f\"'{folder_id}' in parents and trashed=false\"}).GetList()\n",
    "\n",
    "# for file in file_list[:10]:\n",
    "#     print(f\"Downloading {file['title']} from {file['id']}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7faa2971-a938-4d7c-b47d-19ee3e80811b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 파일을 다운 받지않고 바로 메모리에서 처리하기!!!!!!!!! -> io.BytesIO 사용하기\n",
    "# Google Drive에서 이미지와 라벨 파일을 다운로드하여 로컬 경로로 저장\n",
    "def download_drive_folder(folder_id, local_path):\n",
    "    file_list = drive.ListFile({'q': f\"'{folder_id}' in parents and trashed=false\"}).GetList()\n",
    "    if not os.path.exists(local_path):\n",
    "        os.makedirs(local_path)\n",
    "    \n",
    "    for file in file_list:\n",
    "        if file['mimeType'] == 'application/vnd.google-apps.folder':  # 하위 폴더인 경우\n",
    "            subfolder_local_path = os.path.join(local_path, file['title'])\n",
    "            print(f\"Entering folder: {file['title']}\")\n",
    "            download_drive_folder_recursive(file['id'], subfolder_local_path)  # 재귀적으로 하위 폴더 처리\n",
    "        else:\n",
    "            print(f\"Downloading {file['title']} from Google Drive\")\n",
    "            file.GetContentFile(os.path.join(local_path, file['title']))\n",
    "\n",
    "# Google Drive에서 폴더 ID를 이용해 데이터 다운로드\n",
    "image_folder_id = '1Nby_3Fg7NZ-CpLDjimVm9cC3n3imW4Sd'  # Google Drive의 이미지 폴더 ID 입력\n",
    "label_folder_id = '17KDAGcw4JLD3COQHQVYk68AyxUysTGPA'  # Google Drive의 라벨 폴더 ID 입력\n",
    "\n",
    "image_local_path = './images'\n",
    "label_local_path = './labels'\n",
    "\n",
    "# 이미지 및 라벨 다운로드\n",
    "download_drive_folder(image_folder_id, image_local_path)\n",
    "download_drive_folder(label_folder_id, label_local_path)\n",
    "\n",
    "# LaneDataset 클래스 정의\n",
    "class LaneDataset(Dataset):\n",
    "    def __init__(self, image_dir, label_dir, transform=None):\n",
    "        self.image_dir = image_dir\n",
    "        self.label_dir = label_dir\n",
    "        self.transform = transform\n",
    "        self.image_folders = os.listdir(image_dir)\n",
    "        self.label_folders = os.listdir(label_dir)\n",
    "\n",
    "        # 각 폴더 안에 있는 이미지 파일들을 미리 저장\n",
    "        self.image_files = []\n",
    "        for folder in self.image_folders:\n",
    "            folder_path = os.path.join(self.image_dir, folder)\n",
    "            images = os.listdir(folder_path)  # 이미지 파일 리스트\n",
    "            for img_file in images:\n",
    "                self.image_files.append((folder, img_file)) # (폴더명, 이미지 파일명) 저장\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.image_files)  # 모든 이미지 파일의 총 개수\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        # 이미지 파일 정보\n",
    "        folder, img_file = self.image_files[idx]\n",
    "        img_path = os.path.join(self.image_dir, folder, img_file)\n",
    "\n",
    "        # 해당 이미지 파일에 대응하는 라벨 폴더 및 라벨 파일\n",
    "        label_folder_path = os.path.join(self.label_dir, folder)\n",
    "        label_file = os.listdir(label_folder_path)[0]  # 라벨 파일 선택\n",
    "        label_path = os.path.join(label_folder_path, label_file)\n",
    "\n",
    "        # 이미지 로드\n",
    "        image = cv2.imread(img_path)\n",
    "        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "        # 라벨 로드 (JSON 파일에서 차선 종류 및 위반 여부 정보 추출)\n",
    "        with open(label_path, 'r') as f:\n",
    "            label_data = json.load(f)\n",
    "\n",
    "        # 위반 여부 및 차선 종류 추출\n",
    "        violation, lane_type = self.extract_violation(label_path)\n",
    "\n",
    "        # 필요한 경우 데이터 변환 적용\n",
    "        if self.transform:\n",
    "            image = self.transform(image)\n",
    "\n",
    "        return image, violation, lane_type\n",
    "\n",
    "    # JSON 파일에서 위반 여부와 차선 종류 추출 함수\n",
    "    def extract_violation(self, json_file_path):\n",
    "        with open(json_file_path, 'r') as f:\n",
    "            data = json.load(f)\n",
    "\n",
    "        # 위반 여부와 차선 종류 기본값 설정\n",
    "        violation = False  # 기본적으로는 위반 아님\n",
    "        lane_type = None   # 차선 종류는 None을 기본값으로 설정\n",
    "\n",
    "        # \"data_set_info\"에서 \"data\" 항목에 있는 객체 정보 확인\n",
    "        for obj in data['data_set_info']['data']:\n",
    "            object_label = obj['value']['object_Label']\n",
    "\n",
    "            # 위반 여부 판단\n",
    "            if 'vehicle_attribute' in object_label and object_label['vehicle_attribute'] == 'violation':\n",
    "                violation = True  # 위반 차량 있음\n",
    "            # 차선 종류 판단\n",
    "            if 'lane_type' in object_label:\n",
    "                lane_type = object_label['lane_type']\n",
    "\n",
    "        return violation, lane_type\n",
    "\n",
    "# 데이터 변환 설정\n",
    "data_transform = transforms.Compose([\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Resize((224, 224)),  # ResNet 입력 크기와 맞추기\n",
    "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "# 이미지와 라벨 데이터셋 생성\n",
    "dataset = LaneDataset(image_dir=image_local_path, label_dir=label_local_path, transform=data_transform)\n",
    "data_loader = DataLoader(dataset, batch_size=16, shuffle=True)\n",
    "\n",
    "# DataLoader에서 데이터 순차적으로 불러오기\n",
    "for images, (violations, lane_types) in data_loader:\n",
    "    print(images.shape, violations, lane_types)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 161,
   "id": "b97098da-889c-453f-bf5e-5fc70fe647fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/bin/bash: torch: command not found\n"
     ]
    }
   ],
   "source": [
    "# !google auth oauthlib --version\n",
    "!torch --version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "7afab0df-7670-4bcb-aa3e-49961c9d1fed",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33m(Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.\n",
      "\n",
      "Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages \u001b[0m\n",
      "/opt/tljh/user/lib/python3.10/site-packages/jupyterlab/debuglog.py:54: UserWarning: An error occurred.\n",
      "  warnings.warn(\"An error occurred.\")\n",
      "/opt/tljh/user/lib/python3.10/site-packages/jupyterlab/debuglog.py:55: UserWarning: ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).\n",
      "  warnings.warn(msg[-1].strip())\n",
      "/opt/tljh/user/lib/python3.10/site-packages/jupyterlab/debuglog.py:56: UserWarning: See the log file for details: /tmp/jupyterlab-debug-5qghd27m.log\n",
      "  warnings.warn(f\"See the log file for details: {log_path!s}\")\n"
     ]
    }
   ],
   "source": [
    "!jupyter labextension install @jupyterlab/google-drive"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7591e5c2-05fa-4963-a249-f4efb33a2426",
   "metadata": {},
   "outputs": [],
   "source": [
    "# token 설정과 관련된 거 였는데, token 설정 잘 됨!\n",
    "import requests\n",
    "from google.oauth2.credentials import Credentials\n",
    "from google_auth_oauthlib.flow import InstalledAppFlow\n",
    "from google.auth.transport.requests import Request\n",
    "import os\n",
    "\n",
    "# OAuth 2.0 클라이언트 ID를 사용하여 인증\n",
    "SCOPES = ['https://www.googleapis.com/auth/drive.readonly']\n",
    "\n",
    "# OAuth 2.0 인증 설정\n",
    "def authenticate():\n",
    "    creds = None\n",
    "    if os.path.exists('token.json'):\n",
    "        creds = Credentials.from_authorized_user_file('token.json', SCOPES)\n",
    "    if not creds or not creds.valid:\n",
    "        if creds and creds.expired and creds.refresh_token:\n",
    "            creds.refresh(Request())\n",
    "        else:\n",
    "            flow = InstalledAppFlow.from_client_secrets_file('client_secrets.json', SCOPES)\n",
    "            creds = flow.run_local_server(port=0)\n",
    "        with open('token.json', 'w') as token:\n",
    "            token.write(creds.to_json())\n",
    "    return creds\n",
    "\n",
    "# 최상위 폴더의 파일 및 폴더 목록을 가져오기 위한 함수\n",
    "def list_root_files(creds, folder_id):\n",
    "    url = f'https://www.googleapis.com/drive/v3/files?q=\\'{folder_id}\\' in parents'\n",
    "    headers = {'Authorization': f'Bearer {creds.token}'}\n",
    "    params = {\n",
    "        'pageSize': 100,  # 가져올 최대 파일 수\n",
    "        'fields': 'nextPageToken, files(id, name, mimeType)',  # 파일 이름, ID, MIME 타입\n",
    "    }\n",
    "    response = requests.get(url, headers=headers, params=params)\n",
    "    return response.json()\n",
    "\n",
    "# 폴더 ID 설정 (해당 폴더의 ID를 사용)\n",
    "folder_id = '1nor9jn1J30mZN_168SsNj1ArO4duu1VT'  # Colab Notebooks/SpecializedProject/content/차로 위반 영상 데이터/sample_datas \n",
    "# 이 안에 라벨링데이터/TL/A/BLUE 안에 여러 폴더 + 원천데이터/TS1/A/BLUE 안에 여러 폴더\n",
    "\n",
    "creds = authenticate()\n",
    "files = list_root_files(creds, folder_id)\n",
    "print('폴더 ID까지 설정 완료', files)\n",
    "# 최상위 폴더에 있는 파일 및 폴더 출력\n",
    "for file in files.get('files', []):\n",
    "    print(f\"Name: {file['name']}, ID: {file['id']}, MIME Type: {file['mimeType']}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "f261fea8-4ca5-44b1-8407-07193c9d138c",
   "metadata": {},
   "outputs": [
    {
     "ename": "Exception",
     "evalue": "Error downloading file image_file_id_2, status code: 404",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mException\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 107\u001b[0m\n\u001b[1;32m    104\u001b[0m data_loader \u001b[38;5;241m=\u001b[39m DataLoader(dataset, batch_size\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m16\u001b[39m, shuffle\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[1;32m    106\u001b[0m \u001b[38;5;66;03m# DataLoader에서 데이터 순차적으로 불러오기\u001b[39;00m\n\u001b[0;32m--> 107\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m images, (violations, lane_types) \u001b[38;5;129;01min\u001b[39;00m data_loader:\n\u001b[1;32m    108\u001b[0m     \u001b[38;5;28mprint\u001b[39m(images\u001b[38;5;241m.\u001b[39mshape, violations, lane_types)\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py:630\u001b[0m, in \u001b[0;36m_BaseDataLoaderIter.__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    627\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sampler_iter \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    628\u001b[0m     \u001b[38;5;66;03m# TODO(https://github.com/pytorch/pytorch/issues/76750)\u001b[39;00m\n\u001b[1;32m    629\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_reset()  \u001b[38;5;66;03m# type: ignore[call-arg]\u001b[39;00m\n\u001b[0;32m--> 630\u001b[0m data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_next_data\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    631\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_num_yielded \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m    632\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_dataset_kind \u001b[38;5;241m==\u001b[39m _DatasetKind\u001b[38;5;241m.\u001b[39mIterable \u001b[38;5;129;01mand\u001b[39;00m \\\n\u001b[1;32m    633\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_IterableDataset_len_called \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m \\\n\u001b[1;32m    634\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_num_yielded \u001b[38;5;241m>\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_IterableDataset_len_called:\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py:673\u001b[0m, in \u001b[0;36m_SingleProcessDataLoaderIter._next_data\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    671\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_next_data\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m    672\u001b[0m     index \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_next_index()  \u001b[38;5;66;03m# may raise StopIteration\u001b[39;00m\n\u001b[0;32m--> 673\u001b[0m     data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_dataset_fetcher\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfetch\u001b[49m\u001b[43m(\u001b[49m\u001b[43mindex\u001b[49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# may raise StopIteration\u001b[39;00m\n\u001b[1;32m    674\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_pin_memory:\n\u001b[1;32m    675\u001b[0m         data \u001b[38;5;241m=\u001b[39m _utils\u001b[38;5;241m.\u001b[39mpin_memory\u001b[38;5;241m.\u001b[39mpin_memory(data, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_pin_memory_device)\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py:52\u001b[0m, in \u001b[0;36m_MapDatasetFetcher.fetch\u001b[0;34m(self, possibly_batched_index)\u001b[0m\n\u001b[1;32m     50\u001b[0m         data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdataset\u001b[38;5;241m.\u001b[39m__getitems__(possibly_batched_index)\n\u001b[1;32m     51\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m---> 52\u001b[0m         data \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdataset[idx] \u001b[38;5;28;01mfor\u001b[39;00m idx \u001b[38;5;129;01min\u001b[39;00m possibly_batched_index]\n\u001b[1;32m     53\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     54\u001b[0m     data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdataset[possibly_batched_index]\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py:52\u001b[0m, in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m     50\u001b[0m         data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdataset\u001b[38;5;241m.\u001b[39m__getitems__(possibly_batched_index)\n\u001b[1;32m     51\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m---> 52\u001b[0m         data \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdataset\u001b[49m\u001b[43m[\u001b[49m\u001b[43midx\u001b[49m\u001b[43m]\u001b[49m \u001b[38;5;28;01mfor\u001b[39;00m idx \u001b[38;5;129;01min\u001b[39;00m possibly_batched_index]\n\u001b[1;32m     53\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     54\u001b[0m     data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdataset[possibly_batched_index]\n",
      "Cell \u001b[0;32mIn[13], line 56\u001b[0m, in \u001b[0;36mLaneDataset.__getitem__\u001b[0;34m(self, idx)\u001b[0m\n\u001b[1;32m     53\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__getitem__\u001b[39m(\u001b[38;5;28mself\u001b[39m, idx):\n\u001b[1;32m     54\u001b[0m     \u001b[38;5;66;03m# Google Drive에서 이미지를 메모리로 다운로드\u001b[39;00m\n\u001b[1;32m     55\u001b[0m     img_file_id \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mimage_file_ids[idx]\n\u001b[0;32m---> 56\u001b[0m     img_data \u001b[38;5;241m=\u001b[39m \u001b[43mdownload_drive_file\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimg_file_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcreds\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     57\u001b[0m     image \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mfrombuffer(img_data\u001b[38;5;241m.\u001b[39mread(), np\u001b[38;5;241m.\u001b[39muint8)\n\u001b[1;32m     58\u001b[0m     image \u001b[38;5;241m=\u001b[39m cv2\u001b[38;5;241m.\u001b[39mimdecode(image, cv2\u001b[38;5;241m.\u001b[39mIMREAD_COLOR)\n",
      "Cell \u001b[0;32mIn[13], line 40\u001b[0m, in \u001b[0;36mdownload_drive_file\u001b[0;34m(file_id, creds)\u001b[0m\n\u001b[1;32m     38\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m io\u001b[38;5;241m.\u001b[39mBytesIO(response\u001b[38;5;241m.\u001b[39mcontent)\n\u001b[1;32m     39\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m---> 40\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mError downloading file \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, status code: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mresponse\u001b[38;5;241m.\u001b[39mstatus_code\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mException\u001b[0m: Error downloading file image_file_id_2, status code: 404"
     ]
    }
   ],
   "source": [
    "# 파일을 다운 받지않고 바로 메모리에서 처리하기\n",
    "import io\n",
    "import json\n",
    "import requests\n",
    "from google_auth_oauthlib.flow import InstalledAppFlow\n",
    "from google.auth.transport.requests import Request\n",
    "from google.oauth2.credentials import Credentials\n",
    "# import torch\n",
    "\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from torchvision import transforms\n",
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "# OAuth 2.0 인증 설정 (기존 코드와 동일)\n",
    "SCOPES = ['https://www.googleapis.com/auth/drive.readonly']\n",
    "\n",
    "def authenticate():\n",
    "    creds = None\n",
    "    if os.path.exists('token.json'):\n",
    "        creds = Credentials.from_authorized_user_file('token.json', SCOPES)\n",
    "    if not creds or not creds.valid:\n",
    "        if creds and creds.expired and creds.refresh_token:\n",
    "            creds.refresh(Request())\n",
    "        else:\n",
    "            flow = InstalledAppFlow.from_client_secrets_file('client_secrets.json', SCOPES)\n",
    "            creds = flow.run_local_server(port=0)\n",
    "        with open('token.json', 'w') as token:\n",
    "            token.write(creds.to_json())\n",
    "    return creds\n",
    "\n",
    "# Google Drive 파일을 메모리에서 읽는 함수\n",
    "def download_drive_file(file_id, creds):\n",
    "    url = f'https://www.googleapis.com/drive/v3/files/{file_id}?alt=media'\n",
    "    headers = {'Authorization': f'Bearer {creds.token}'}\n",
    "    response = requests.get(url, headers=headers)\n",
    "    if response.status_code == 200:\n",
    "        return io.BytesIO(response.content)\n",
    "    else:\n",
    "        raise Exception(f\"Error downloading file {file_id}, status code: {response.status_code}\")\n",
    "\n",
    "# 이미지와 라벨 데이터셋 정의 (메모리에서 처리)\n",
    "class LaneDataset(Dataset):\n",
    "    def __init__(self, image_file_ids, label_file_ids, creds, transform=None):\n",
    "        self.image_file_ids = image_file_ids\n",
    "        self.label_file_ids = label_file_ids\n",
    "        self.transform = transform\n",
    "        self.creds = creds\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.image_file_ids)  # 모든 이미지 파일의 총 개수\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        # Google Drive에서 이미지를 메모리로 다운로드\n",
    "        img_file_id = self.image_file_ids[idx]\n",
    "        img_data = download_drive_file(img_file_id, self.creds)\n",
    "        image = np.frombuffer(img_data.read(), np.uint8)\n",
    "        image = cv2.imdecode(image, cv2.IMREAD_COLOR)\n",
    "        image = cv2.cvtColor(image, cv2.COLOR_GR2RGB)\n",
    "\n",
    "        # Google Drive에서 라벨 데이터를 메모리로 다운로드\n",
    "        label_file_id = self.label_file_ids[idx]\n",
    "        label_data = download_drive_file(label_file_id, self.creds)\n",
    "        label_json = json.load(label_data)\n",
    "\n",
    "        # 위반 여부 및 차선 종류 추출\n",
    "        violation, lane_type = self.extract_violation(label_json)\n",
    "\n",
    "        # 필요한 경우 데이터 변환 적용\n",
    "        if self.transform:\n",
    "            image = self.transform(image)\n",
    "\n",
    "        return image, violation, lane_type\n",
    "\n",
    "    # JSON 파일에서 위반 여부와 차선 종류 추출 함수\n",
    "    def extract_violation(self, label_data):\n",
    "        violation = False  # 기본적으로는 위반 아님\n",
    "        lane_type = None   # 차선 종류는 None을 기본값으로 설정\n",
    "\n",
    "        for obj in label_data['data_set_info']['data']:\n",
    "            object_label = obj['value']['object_Label']\n",
    "            if 'vehicle_attribute' in object_label and object_label['vehicle_attribute'] == 'violation':\n",
    "                violation = True\n",
    "            if 'lane_type' in object_label:\n",
    "                lane_type = object_label['lane_type']\n",
    "\n",
    "        return violation, lane_type\n",
    "\n",
    "# 데이터 변환 설정\n",
    "data_transform = transforms.Compose([\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Resize((224, 224)),  # ResNet 입력 크기와 맞추기\n",
    "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "# Google Drive에서 가져올 이미지와 라벨 파일 ID 목록\n",
    "image_file_ids = ['image_file_id_1', 'image_file_id_2']  # 실제 이미지 파일 ID 입력\n",
    "label_file_ids = ['label_file_id_1', 'label_file_id_2']  # 실제 라벨 파일 ID 입력\n",
    "\n",
    "creds = authenticate()\n",
    "\n",
    "# 이미지와 라벨 데이터셋 생성\n",
    "dataset = LaneDataset(image_file_ids=image_file_ids, label_file_ids=label_file_ids, creds=creds, transform=data_transform)\n",
    "data_loader = DataLoader(dataset, batch_size=16, shuffle=True)\n",
    "\n",
    "# DataLoader에서 데이터 순차적으로 불러오기\n",
    "for images, (violations, lane_types) in data_loader:\n",
    "    print(images.shape, violations, lane_types)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a41a66c3-90c5-4b7b-9045-72fcd7b72e79",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mName: torch\n",
      "Version: 2.4.1+cu118\n",
      "Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration\n",
      "Home-page: https://pytorch.org/\n",
      "Author: PyTorch Team\n",
      "Author-email: packages@pytorch.org\n",
      "License: BSD-3\n",
      "Location: /home/j-j11a303/.local/lib/python3.10/site-packages\n",
      "Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu11, nvidia-cuda-cupti-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, nvidia-cufft-cu11, nvidia-curand-cu11, nvidia-cusolver-cu11, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, sympy, triton, typing-extensions\n",
      "Required-by: torchaudio, torchvision\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -ympy (/home/j-j11a303/.local/lib/python3.10/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mName: torchvision\n",
      "Version: 0.19.1+cu118\n",
      "Summary: image and video datasets and models for torch deep learning\n",
      "Home-page: https://github.com/pytorch/vision\n",
      "Author: PyTorch Core Team\n",
      "Author-email: soumith@pytorch.org\n",
      "License: BSD\n",
      "Location: /home/j-j11a303/.local/lib/python3.10/site-packages\n",
      "Requires: numpy, pillow, torch\n",
      "Required-by: \n"
     ]
    }
   ],
   "source": [
    "!pip show torch\n",
    "!pip show torchvision"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b786ef6a-8d11-434c-9706-f8fb3d3ec171",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "urecar",
   "language": "python",
   "name": "urecar"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
